import type { LinhaFila, OsDetalheSnapshot, SalaSnapshot } from "@/lib/ec/snapshot-tipos";

function detalheDemo(parcial: Partial<OsDetalheSnapshot> & Pick<OsDetalheSnapshot, "os" | "equipamento" | "tag" | "setor">): OsDetalheSnapshot {
  return {
    oficina: "ENGENHARIA CLÍNICA",
    responsavel: "TECNICO DEMO",
    situacaoOs: "ABERTA",
    criticidade: "ALTA",
    etapa: "Sem 1º atendimento",
    aberto: true,
    solicitacao: "Equipamento com falha — solicitar verificação.",
    ocorrencia: "Não liga / alarme",
    servico: "—",
    observacaoOs: "—",
    pendencia: "—",
    observacaoPendencia: "—",
    manutencaoExterna: false,
    assistencia: "—",
    pendenciaCompra: false,
    abertura: "01/10/2026 08:12",
    primeiroAtendimento: "—",
    fechamento: "—",
    tipoManutencao: "A - CORRETIVA",
    prioridade: "ALTA - 2 HORAS",
    requisitante: "ENFERMAGEM",
    ...parcial,
  };
}

/** Fixture local para QA visual da TV (`/sala/agora?demo=1`). Não usado em produção. */
export function snapshotDemoAgora(): SalaSnapshot {
  const fila: LinhaFila[] = [
    {
      os: "202609698",
      equipamento: "BISTURI ELETRÔNICO",
      tag: "HSJ-01079",
      setor: "CENTRO CIRÚRGICO - 10A",
      situacao: "GRAVE",
      criticidade: "ALTA",
      idade: "5d 8h",
      parado: true,
      compra: false,
    },
    {
      os: "202609701",
      equipamento: "MONITOR MULTIPARAMÉTRICO",
      tag: "HSJ-00812",
      setor: "UTI ADULTO - 3B",
      situacao: "GRAVE",
      criticidade: "ALTA",
      idade: "3d 2h",
      parado: true,
      compra: false,
    },
    {
      os: "202609655",
      equipamento: "VENTILADOR PULMONAR NEONATAL DE TRANSPORTE",
      tag: "HSJ-00440",
      setor: "UTI NEONATAL",
      situacao: "ATRASADA",
      criticidade: "ALTA",
      idade: "2d 4h",
      parado: true,
      compra: true,
    },
    {
      os: "202609710",
      equipamento: "DESFIBRILADOR",
      tag: "HSJ-00221",
      setor: "PRONTO SOCORRO",
      situacao: "ATRASADA",
      criticidade: "MÉDIA",
      idade: "1d 6h",
      parado: true,
      compra: false,
    },
    {
      os: "202609720",
      equipamento: "BOMBA DE INFUSÃO",
      tag: "HSJ-01550",
      setor: "CLÍNICA MÉDICA - 5A",
      situacao: "VENCE LOGO",
      criticidade: "MÉDIA",
      idade: "9h",
      parado: false,
      compra: false,
    },
    {
      os: "202609722",
      equipamento: "CARDIOVERSOR",
      tag: "HSJ-00301",
      setor: "CENTRO CIRÚRGICO - 10B",
      situacao: "NO PRAZO",
      criticidade: "BAIXA",
      idade: "3h",
      parado: false,
      compra: false,
    },
  ];

  const grave = fila.filter((item) => item.situacao === "GRAVE");
  const fora = fila.filter((item) => item.situacao === "GRAVE" || item.situacao === "ATRASADA");

  return {
    atualizadoEm: new Date().toISOString(),
    relogio: "21:51",
    plantao: true,
    plantaoTexto: "Fora do horário da EC (7h–17h). Plantão: Manutenção. Prazos voltam às 07:00.",
    segundos: 30,
    sequencia: [
      "agora",
      "fluxo",
      "compras",
      "agora",
      "envelhecimento",
      "programadas",
      "agora",
      "ciclo-de-vida",
      "indicadores",
      "processos",
    ],
    alertas: [],
    blocos: [{ id: "os", fonte: "manual" }],
    detalhes: {
      "agora.grave": grave,
      "agora.fora-do-prazo": fora,
      "agora.sem-primeiro": fila,
      "agora.parados": [
        { tag: "HSJ-01102", equipamento: "UMIDIFICADOR", setor: "CME", tempo: "166d", os: "202608100" },
        { tag: "HSJ-01079", equipamento: "BISTURI ELETRÔNICO", setor: "CENTRO CIRÚRGICO - 10A", tempo: "5d", os: "202609698" },
        { tag: "HSJ-00812", equipamento: "MONITOR MULTIPARAMÉTRICO", setor: "UTI ADULTO - 3B", tempo: "3d", os: "202609701" },
        { tag: "HSJ-00221", equipamento: "DESFIBRILADOR", setor: "PRONTO SOCORRO", tempo: "1d", os: "202609710" },
      ],
    },
    osDetalhes: {
      "202609698": detalheDemo({
        os: "202609698",
        equipamento: "BISTURI ELETRÔNICO",
        tag: "HSJ-01079",
        setor: "CENTRO CIRÚRGICO - 10A",
        solicitacao: "Não corta — pedalar sem efeito. Urgente para cirurgia.",
        ocorrencia: "Falha de potência",
        manutencaoExterna: true,
        assistencia: "EXT — enviada para assistência do fabricante",
        etapa: "Reparo externo",
        abertura: "01/10/2026 07:40",
      }),
      "202609701": detalheDemo({
        os: "202609701",
        equipamento: "MONITOR MULTIPARAMÉTRICO",
        tag: "HSJ-00812",
        setor: "UTI ADULTO - 3B",
        solicitacao: "Tela apagada; cabo SpO2 intermitente.",
        pendenciaCompra: true,
        pendencia: "Aguardando compra de cabo SpO2",
        observacaoPendencia: "Cotação enviada ao almoxarifado",
        etapa: "Aguarda peça/compra",
        criticidade: "ALTA",
      }),
      "202609655": detalheDemo({
        os: "202609655",
        equipamento: "VENTILADOR PULMONAR NEONATAL DE TRANSPORTE",
        tag: "HSJ-00440",
        setor: "UTI NEONATAL",
        solicitacao: "Alarme de pressão persistente.",
        pendenciaCompra: true,
        pendencia: "Pendência compra — válvula",
        criticidade: "ALTA",
        etapa: "Aguarda peça/compra",
      }),
      "202609710": detalheDemo({
        os: "202609710",
        equipamento: "DESFIBRILADOR",
        tag: "HSJ-00221",
        setor: "PRONTO SOCORRO",
        solicitacao: "Bateria não segura carga.",
        criticidade: "MÉDIA",
      }),
      "202609720": detalheDemo({
        os: "202609720",
        equipamento: "BOMBA DE INFUSÃO",
        tag: "HSJ-01550",
        setor: "CLÍNICA MÉDICA - 5A",
        solicitacao: "Oclusão falsa frequente.",
        criticidade: "MÉDIA",
        etapa: "Em atendimento",
        primeiroAtendimento: "06/10/2026 09:10",
      }),
      "202609722": detalheDemo({
        os: "202609722",
        equipamento: "CARDIOVERSOR",
        tag: "HSJ-00301",
        setor: "CENTRO CIRÚRGICO - 10B",
        solicitacao: "Teste preventivo pós-uso.",
        criticidade: "BAIXA",
      }),
      "202608100": detalheDemo({
        os: "202608100",
        equipamento: "UMIDIFICADOR",
        tag: "HSJ-01102",
        setor: "CME",
        solicitacao: "Equipamento parado há meses — avaliar baixa.",
        etapa: "Em atendimento",
        abertura: "12/04/2026 10:00",
        primeiroAtendimento: "12/04/2026 14:20",
      }),
    },
    agora: {
      grave: grave.length,
      foraDoPrazo: fora.length,
      semPrimeiro: fila.length,
      parados: 22,
      parque: 1840,
      gravePct: 0.3,
      foraDoPrazoPct: 0.3,
      semPrimeiroPct: 0.3,
      paradosPct: 1.2,
      proxyParada: "Proxy: OS demanda aberta ou flag de parada no mês.",
      plano: [
        { tipo: "Preventiva", faltam: null, percentual: null },
        { tipo: "Calibração", faltam: null, percentual: null },
        { tipo: "TSE", faltam: null, percentual: null },
      ],
      planoAviso: "Sem plano ancorado para o mês nestes tipos.",
      paradosMaisTempo: [
        { nome: "UMIDIFICADOR", setor: "CME", tempo: "166d" },
        { nome: "AUTOCLAVE", setor: "CME", tempo: "41d" },
        { nome: "MONITOR FETAL", setor: "CENTRO OBSTÉTRICO", tempo: "28d" },
        { nome: "ASPIRADOR CIRÚRGICO", setor: "CENTRO CIRÚRGICO", tempo: "19d" },
      ],
      fila,
      filaOcultas: 2,
      hojeAbertas: 1,
      hojeFechadas: 4,
      semanaAbertas: 12,
      semanaFechadas: 18,
      primeiroNoPrazo30d: 86,
      tpm30d: 368,
      disponibilidadeCriticos: 97.2,
    },
    fluxo: {
      entraramHoje: 0,
      encerradasHoje: 0,
      etapas: [],
      entraram: [],
      entraramOcultas: 0,
      equipeAviso: "Demo: fluxo não preenchido.",
    },
    envelhecimento: {
      proxy: "Demo",
      idadeMediaDias: null,
      aguardandoTerceiros: 0,
      semMovimentoMais7: null,
      pendenciaSemMotivo: 0,
      faixas: [],
      maisAntigas: [],
    },
    compras: {
      aviso: "Demo",
      fonte: "ordens_compra",
      configurado: false,
      aguardaResposta: 0,
      aguardaRespostaMaisAntigo: null,
      aguardaEntrega: 0,
      aguardaEntregaMaisAntiga: null,
      entreguesMes: 0,
      mediaPedidoOrdem: null,
      mediaOrdemEntrega: null,
      mediaPontaAPonta: null,
      percentualComOs: null,
      semOs: 0,
      totalOrdens: 0,
      pedidosLegadoAbertos: 0,
      pedidos: [],
    },
    programadas: {
      aviso: "Demo",
      proxy: "Demo",
      cumprimento: null,
      previstos: 0,
      executados: 0,
      faltam: 0,
      porTipo: [],
      pendentes: [],
      impedimentos: [],
    },
    ciclo: {
      trilha: [
        { etapa: "Aquisição", quantidade: 12 },
        { etapa: "Recebimento", quantidade: null },
        { etapa: "Em uso", quantidade: 1840 },
        { etapa: "Fim de vida", quantidade: 38 },
        { etapa: "Inservível", quantidade: 1141 },
      ],
      histograma: [
        { faixa: "0 a 5 anos", emVida: 420, alem: 12 },
        { faixa: "6 a 10 anos", emVida: 510, alem: 28 },
        { faixa: "11 a 15 anos", emVida: 380, alem: 45 },
        { faixa: "16 a 20 anos", emVida: 210, alem: 62 },
        { faixa: "mais de 20", emVida: 95, alem: 78 },
      ],
      fimDeVida: [
        {
          tag: "HSJ-00440",
          equipamento: "VENTILADOR PULMONAR",
          pontos: 3,
          criterios: "fim de vida · sem peça / descontinuado · 4+ corretivas",
          valorSubstituicao: "R$ 186.000",
        },
        {
          tag: "HSJ-01079",
          equipamento: "BISTURI ELETRÔNICO",
          pontos: 2,
          criterios: "fim de vida · custo ≥ 50%",
          valorSubstituicao: "R$ 42.500",
        },
        {
          tag: "HSJ-00812",
          equipamento: "MONITOR MULTIPARAMÉTRICO",
          pontos: 2,
          criterios: "sem peça / descontinuado · 4+ corretivas",
          valorSubstituicao: "R$ 28.900",
        },
        {
          tag: "HSJ-00221",
          equipamento: "DESFIBRILADOR",
          pontos: 1,
          criterios: "fim de vida",
          valorSubstituicao: "R$ 55.000",
        },
        {
          tag: "HSJ-01550",
          equipamento: "BOMBA DE INFUSÃO",
          pontos: 1,
          criterios: "sem peça / descontinuado",
          valorSubstituicao: "R$ 9.800",
        },
      ],
      valorSubstituicaoFimDeVida: "R$ 4,2 mi",
      quantidadeFimDeVida: 38,
      avisoDescontinuado:
        "Sem peça / descontinuado = EndOfService já passou. Fim de vida = EndOfLife (Anvisa).",
      maisAntigos: [
        { tag: "HSJ-00012", equipamento: "RAIO-X MÓVEL", idade: "24 anos", fim: "15/03/2027" },
        { tag: "HSJ-00048", equipamento: "AUTOCLAVE", idade: "22 anos", fim: "01/08/2028" },
      ],
      emCiclo: 1620,
      vencem5Anos: 17,
      vencem10Anos: 32,
      previsaoEol: [
        {
          ano: "2027",
          quantidade: 5,
          itens: [
            {
              tag: "HSJ-00440",
              equipamento: "VENTILADOR PULMONAR",
              setor: "UTI ADULTO",
              data: "15/03/2027",
              valorSubstituicao: "R$ 186.000",
            },
            {
              tag: "HSJ-01079",
              equipamento: "BISTURI ELETRÔNICO",
              setor: "CENTRO CIRÚRGICO",
              data: "01/06/2027",
              valorSubstituicao: "R$ 42.500",
            },
            {
              tag: "HSJ-00812",
              equipamento: "MONITOR MULTIPARAMÉTRICO",
              setor: "PRONTO SOCORRO",
              data: "22/09/2027",
              valorSubstituicao: "R$ 28.900",
            },
            {
              tag: "HSJ-00221",
              equipamento: "DESFIBRILADOR",
              setor: "UTI NEONATAL",
              data: "10/11/2027",
              valorSubstituicao: "R$ 55.000",
            },
            {
              tag: "HSJ-01550",
              equipamento: "BOMBA DE INFUSÃO",
              setor: "ENFERMARIA A",
              data: "30/12/2027",
              valorSubstituicao: "R$ 9.800",
            },
          ],
        },
        {
          ano: "2028",
          quantidade: 3,
          itens: [
            {
              tag: "HSJ-00048",
              equipamento: "AUTOCLAVE",
              setor: "CME",
              data: "01/08/2028",
              valorSubstituicao: "R$ 120.000",
            },
            {
              tag: "HSJ-01102",
              equipamento: "RAIO-X MÓVEL",
              setor: "RADIOLOGIA",
              data: "14/04/2028",
              valorSubstituicao: "R$ 310.000",
            },
            {
              tag: "HSJ-00677",
              equipamento: "FOCO CIRÚRGICO",
              setor: "CENTRO CIRÚRGICO",
              data: "20/10/2028",
              valorSubstituicao: "R$ 48.000",
            },
          ],
        },
        {
          ano: "2029",
          quantidade: 4,
          itens: [
            {
              tag: "HSJ-00331",
              equipamento: "ECOCARDÍOGRAFO",
              setor: "CARDIOLOGIA",
              data: "05/02/2029",
              valorSubstituicao: "R$ 420.000",
            },
            {
              tag: "HSJ-01990",
              equipamento: "MESA CIRÚRGICA",
              setor: "CENTRO CIRÚRGICO",
              data: "18/07/2029",
              valorSubstituicao: "R$ 95.000",
            },
            {
              tag: "HSJ-00714",
              equipamento: "BOMBA DE INFUSÃO",
              setor: "UTI ADULTO",
              data: "03/09/2029",
              valorSubstituicao: "R$ 11.200",
            },
            {
              tag: "HSJ-01208",
              equipamento: "MONITOR MULTIPARAMÉTRICO",
              setor: "UTI PED",
              data: "28/11/2029",
              valorSubstituicao: "R$ 32.000",
            },
          ],
        },
        {
          ano: "2030",
          quantidade: 3,
          itens: [
            {
              tag: "HSJ-02001",
              equipamento: "VENTILADOR PULMONAR",
              setor: "UTI ADULTO",
              data: "12/01/2030",
              valorSubstituicao: "R$ 175.000",
            },
            {
              tag: "HSJ-02045",
              equipamento: "DESFIBRILADOR",
              setor: "PRONTO SOCORRO",
              data: "08/05/2030",
              valorSubstituicao: "R$ 58.000",
            },
            {
              tag: "HSJ-02110",
              equipamento: "AUTOCLAVE",
              setor: "CME",
              data: "19/09/2030",
              valorSubstituicao: "R$ 98.000",
            },
          ],
        },
        {
          ano: "2031",
          quantidade: 2,
          itens: [
            {
              tag: "HSJ-02200",
              equipamento: "BISTURI ELETRÔNICO",
              setor: "CENTRO CIRÚRGICO",
              data: "01/03/2031",
              valorSubstituicao: "R$ 45.000",
            },
            {
              tag: "HSJ-02255",
              equipamento: "FOCO CIRÚRGICO",
              setor: "CENTRO CIRÚRGICO",
              data: "15/08/2031",
              valorSubstituicao: "R$ 52.000",
            },
          ],
        },
        {
          ano: "2032",
          quantidade: 4,
          itens: [
            {
              tag: "HSJ-02301",
              equipamento: "MONITOR MULTIPARAMÉTRICO",
              setor: "ENFERMARIA B",
              data: "20/02/2032",
              valorSubstituicao: "R$ 27.500",
            },
            {
              tag: "HSJ-02340",
              equipamento: "BOMBA DE INFUSÃO",
              setor: "UTI NEONATAL",
              data: "11/06/2032",
              valorSubstituicao: "R$ 10.400",
            },
            {
              tag: "HSJ-02388",
              equipamento: "RAIO-X MÓVEL",
              setor: "RADIOLOGIA",
              data: "04/09/2032",
              valorSubstituicao: "R$ 290.000",
            },
            {
              tag: "HSJ-02412",
              equipamento: "ECOCARDÍOGRAFO",
              setor: "CARDIOLOGIA",
              data: "22/12/2032",
              valorSubstituicao: "R$ 390.000",
            },
          ],
        },
        {
          ano: "2033",
          quantidade: 3,
          itens: [
            {
              tag: "HSJ-02500",
              equipamento: "MESA CIRÚRGICA",
              setor: "CENTRO CIRÚRGICO",
              data: "07/04/2033",
              valorSubstituicao: "R$ 88.000",
            },
            {
              tag: "HSJ-02533",
              equipamento: "VENTILADOR PULMONAR",
              setor: "UTI PED",
              data: "16/07/2033",
              valorSubstituicao: "R$ 168.000",
            },
            {
              tag: "HSJ-02570",
              equipamento: "DESFIBRILADOR",
              setor: "UTI ADULTO",
              data: "29/11/2033",
              valorSubstituicao: "R$ 61.000",
            },
          ],
        },
        {
          ano: "2034",
          quantidade: 2,
          itens: [
            {
              tag: "HSJ-02610",
              equipamento: "AUTOCLAVE",
              setor: "CME",
              data: "03/05/2034",
              valorSubstituicao: "R$ 105.000",
            },
            {
              tag: "HSJ-02644",
              equipamento: "MONITOR MULTIPARAMÉTRICO",
              setor: "PRONTO SOCORRO",
              data: "21/10/2034",
              valorSubstituicao: "R$ 30.000",
            },
          ],
        },
        {
          ano: "2035",
          quantidade: 3,
          itens: [
            {
              tag: "HSJ-02701",
              equipamento: "BISTURI ELETRÔNICO",
              setor: "CENTRO CIRÚRGICO",
              data: "14/01/2035",
              valorSubstituicao: "R$ 47.000",
            },
            {
              tag: "HSJ-02755",
              equipamento: "BOMBA DE INFUSÃO",
              setor: "ENFERMARIA A",
              data: "09/06/2035",
              valorSubstituicao: "R$ 9.500",
            },
            {
              tag: "HSJ-02790",
              equipamento: "FOCO CIRÚRGICO",
              setor: "CENTRO CIRÚRGICO",
              data: "30/09/2035",
              valorSubstituicao: "R$ 50.000",
            },
          ],
        },
        {
          ano: "2036",
          quantidade: 3,
          itens: [
            {
              tag: "HSJ-02820",
              equipamento: "RAIO-X MÓVEL",
              setor: "RADIOLOGIA",
              data: "02/03/2036",
              valorSubstituicao: "R$ 305.000",
            },
            {
              tag: "HSJ-02860",
              equipamento: "ECOCARDÍOGRAFO",
              setor: "CARDIOLOGIA",
              data: "18/08/2036",
              valorSubstituicao: "R$ 410.000",
            },
            {
              tag: "HSJ-02899",
              equipamento: "VENTILADOR PULMONAR",
              setor: "UTI ADULTO",
              data: "12/12/2036",
              valorSubstituicao: "R$ 190.000",
            },
          ],
        },
      ],
    },
    indicadores: { meses: [], cartoes: [] },
    processos: {
      itens: [],
      foraDoHorario: 0,
      melhorias: "Demo",
      melhoriasLista: [],
    },
  };
}
