import type { LinhaFila, SalaSnapshot } from "@/lib/ec/snapshot-tipos";

/** Fixture local para QA visual da TV (`/sala/agora?demo=1`). Não usado em produção. */
export function snapshotDemoAgora(): SalaSnapshot {
  const fila: LinhaFila[] = [
    {
      os: "202609698",
      equipamento: "BISTURI ELETRÔNICO",
      tag: "HSJ-01079",
      setor: "CENTRO CIRÚRGICO - 10A",
      situacao: "GRAVE",
      criticidade: "ALTA",
      idade: "5d 8h",
      parado: true,
      compra: false,
    },
    {
      os: "202609701",
      equipamento: "MONITOR MULTIPARAMÉTRICO",
      tag: "HSJ-00812",
      setor: "UTI ADULTO - 3B",
      situacao: "GRAVE",
      criticidade: "ALTA",
      idade: "3d 2h",
      parado: true,
      compra: false,
    },
    {
      os: "202609655",
      equipamento: "VENTILADOR PULMONAR",
      tag: "HSJ-00440",
      setor: "UTI NEONATAL",
      situacao: "ATRASADA",
      criticidade: "ALTA",
      idade: "2d 4h",
      parado: false,
      compra: true,
    },
    {
      os: "202609710",
      equipamento: "DESFIBRILADOR",
      tag: "HSJ-00221",
      setor: "PRONTO SOCORRO",
      situacao: "ATRASADA",
      criticidade: "MÉDIA",
      idade: "1d 6h",
      parado: true,
      compra: false,
    },
    {
      os: "202609720",
      equipamento: "BOMBA DE INFUSÃO",
      tag: "HSJ-01550",
      setor: "CLÍNICA MÉDICA - 5A",
      situacao: "VENCE LOGO",
      criticidade: "MÉDIA",
      idade: "9h",
      parado: false,
      compra: false,
    },
    {
      os: "202609722",
      equipamento: "CARDIOVERSOR",
      tag: "HSJ-00301",
      setor: "CENTRO CIRÚRGICO - 10B",
      situacao: "NO PRAZO",
      criticidade: "BAIXA",
      idade: "3h",
      parado: false,
      compra: false,
    },
  ];

  const grave = fila.filter((item) => item.situacao === "GRAVE");
  const fora = fila.filter((item) => item.situacao === "GRAVE" || item.situacao === "ATRASADA");

  return {
    atualizadoEm: new Date().toISOString(),
    relogio: "21:51",
    plantao: true,
    plantaoTexto: "Fora do horário da EC (7h–17h). Plantão: Manutenção. Prazos voltam às 07:00.",
    segundos: 30,
    sequencia: [
      "agora",
      "fluxo",
      "compras",
      "agora",
      "envelhecimento",
      "programadas",
      "agora",
      "ciclo-de-vida",
      "indicadores",
      "processos",
    ],
    alertas: [],
    blocos: [{ id: "os", fonte: "manual" }],
    detalhes: {
      "agora.grave": grave,
      "agora.fora-do-prazo": fora,
      "agora.sem-primeiro": fila,
      "agora.parados": [
        { tag: "HSJ-01102", equipamento: "UMIDIFICADOR", setor: "CME", tempo: "166d", os: "202608100" },
        { tag: "HSJ-01079", equipamento: "BISTURI ELETRÔNICO", setor: "CENTRO CIRÚRGICO - 10A", tempo: "5d", os: "202609698" },
        { tag: "HSJ-00812", equipamento: "MONITOR MULTIPARAMÉTRICO", setor: "UTI ADULTO - 3B", tempo: "3d", os: "202609701" },
        { tag: "HSJ-00221", equipamento: "DESFIBRILADOR", setor: "PRONTO SOCORRO", tempo: "1d", os: "202609710" },
      ],
    },
    agora: {
      grave: 5,
      foraDoPrazo: 6,
      semPrimeiro: 6,
      parados: 22,
      parque: 1840,
      gravePct: 0.3,
      foraDoPrazoPct: 0.3,
      semPrimeiroPct: 0.3,
      paradosPct: 1.2,
      proxyParada: "Proxy: OS demanda aberta ou flag de parada no mês.",
      plano: [
        { tipo: "Preventiva", faltam: null, percentual: null },
        { tipo: "Calibração", faltam: null, percentual: null },
        { tipo: "TSE", faltam: null, percentual: null },
      ],
      planoAviso: "Sem plano ancorado para o mês nestes tipos.",
      paradosMaisTempo: [
        { nome: "UMIDIFICADOR", setor: "CME", tempo: "166d" },
        { nome: "AUTOCLAVE", setor: "CME", tempo: "41d" },
        { nome: "MONITOR FETAL", setor: "CENTRO OBSTÉTRICO", tempo: "28d" },
        { nome: "ASPIRADOR CIRÚRGICO", setor: "CENTRO CIRÚRGICO", tempo: "19d" },
      ],
      fila,
      filaOcultas: 2,
      hojeAbertas: 1,
      hojeFechadas: 4,
      semanaAbertas: 12,
      semanaFechadas: 18,
      primeiroNoPrazo30d: 86,
      tpm30d: 368,
      disponibilidadeCriticos: 97.2,
    },
    fluxo: {
      entraramHoje: 0,
      encerradasHoje: 0,
      etapas: [],
      entraram: [],
      entraramOcultas: 0,
      equipeAviso: "Demo: fluxo não preenchido.",
    },
    envelhecimento: {
      proxy: "Demo",
      idadeMediaDias: null,
      aguardandoTerceiros: 0,
      semMovimentoMais7: null,
      pendenciaSemMotivo: 0,
      faixas: [],
      maisAntigas: [],
    },
    compras: {
      aviso: "Demo",
      fonte: "ordens_compra",
      configurado: false,
      aguardaResposta: 0,
      aguardaRespostaMaisAntigo: null,
      aguardaEntrega: 0,
      aguardaEntregaMaisAntiga: null,
      entreguesMes: 0,
      mediaPedidoOrdem: null,
      mediaOrdemEntrega: null,
      mediaPontaAPonta: null,
      percentualComOs: null,
      semOs: 0,
      totalOrdens: 0,
      pedidosLegadoAbertos: 0,
      pedidos: [],
    },
    programadas: {
      aviso: "Demo",
      proxy: "Demo",
      cumprimento: null,
      previstos: 0,
      executados: 0,
      faltam: 0,
      porTipo: [],
      pendentes: [],
      impedimentos: [],
    },
    ciclo: {
      trilha: [],
      histograma: [],
      fimDeVida: [],
      valorSubstituicaoFimDeVida: "—",
      quantidadeFimDeVida: 0,
      avisoDescontinuado: "Demo",
      maisAntigos: [],
      emCiclo: 0,
      vencem5Anos: 0,
      previsaoEol: [],
    },
    indicadores: { meses: [], cartoes: [] },
    processos: {
      itens: [],
      foraDoHorario: 0,
      melhorias: "Demo",
      melhoriasLista: [],
    },
  };
}
